// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6kzkYTpwXT34U4-mmDkywhOzgF19DF2o',
    appId: '1:488978580208:web:740a2b6e0c4f969f753835',
    messagingSenderId: '488978580208',
    projectId: 'ragsafesl',
    authDomain: 'ragsafesl.firebaseapp.com',
    storageBucket: 'ragsafesl.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhZ43p5A1UEhzCYrDw5kY_jnvmuFkZMBk',
    appId: '1:488978580208:android:14ee68c15ebcc8a9753835',
    messagingSenderId: '488978580208',
    projectId: 'ragsafesl',
    storageBucket: 'ragsafesl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8eEwBpRX65bgoFyMpK4QJh-3xKIp0-B0',
    appId: '1:488978580208:ios:27f9ff69e13a4e93753835',
    messagingSenderId: '488978580208',
    projectId: 'ragsafesl',
    storageBucket: 'ragsafesl.firebasestorage.app',
    iosBundleId: 'com.example.ragsafeSl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8eEwBpRX65bgoFyMpK4QJh-3xKIp0-B0',
    appId: '1:488978580208:ios:27f9ff69e13a4e93753835',
    messagingSenderId: '488978580208',
    projectId: 'ragsafesl',
    storageBucket: 'ragsafesl.firebasestorage.app',
    iosBundleId: 'com.example.ragsafeSl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6kzkYTpwXT34U4-mmDkywhOzgF19DF2o',
    appId: '1:488978580208:web:ef330396db35a5d7753835',
    messagingSenderId: '488978580208',
    projectId: 'ragsafesl',
    authDomain: 'ragsafesl.firebaseapp.com',
    storageBucket: 'ragsafesl.firebasestorage.app',
  );
}
